[versions]
arrowVersion = "2.2.1.1"
jupiterVersion = "6.0.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.3.0" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version = "2.3.0" }
kotlin-js = { id = "org.jetbrains.kotlin.js", version = "2.3.0" }
jesperancinha-omni = { id = "org.jesperancinha.plugins.omni", version = "0.4.5" }
google-ksp = { id = "com.google.devtools.ksp", version = "2.3.4" }

[libraries]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "jupiterVersion" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiterVersion" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiterVersion" }
arrow-stack = { group = "io.arrow-kt", name = "arrow-stack", version.ref = "arrowVersion" }
arrow-core = { group = "io.arrow-kt", name = "arrow-core", version.ref = "arrowVersion" }
arrow-fx-coroutines = { group = "io.arrow-kt", name = "arrow-fx-coroutines", version.ref = "arrowVersion" }
arrow-analysis-types-jvm = { group = "io.arrow-kt", name = "arrow-analysis-types-jvm", version = "2.0.2" }
arrow-optics-ksp-plugin = { group = "io.arrow-kt", name = "arrow-optics-ksp-plugin", version.ref = "arrowVersion" }
consolerizer = { group = "org.jesperancinha.console", name = "consolerizer", version = "2.2.3" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version = "2.3.0" }
kotest-assertions-core-jvm = { group = "io.kotest", name = "kotest-assertions-core-jvm", version = "6.0.7" }
assertj-core = { group = "org.assertj", name = "assertj-core", version = "3.27.6" }
kotest-runner-junit5-jvm = { group = "io.kotest", name = "kotest-runner-junit5-jvm", version = "6.0.7" }
kotest-framework-engine-jvm = { group = "io.kotest", name = "kotest-framework-engine-jvm", version = "6.0.7" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version = "6.0.7" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version = "2.3.0" }
google-gson = { group = "com.google.code.gson", name = "gson", version = "2.13.2" }
junit-bom = { group = "org.junit", name = "junit-bom", version = "6.0.1" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core-jvm", version = "6.0.7" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.17" }